config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'comments#index'

  resources :comments
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: comments
#
#  id         :bigint(8)        not null, primary key
#  content    :text
#  privacy    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Comment < ApplicationRecord
  PRIVACIES = [ 'public', 'private' ]
  has_rich_text :content

  # Validations
  validates     :content, presence: true
  validates     :privacy, presence: true, inclusion: { in: PRIVACIES }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  add_flash_types :success, :error
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  def index
    @comments = Comment.all
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)

    if @comment.save
      redirect_to({ action: :index }, flash: { success: 'Comment was successfully created' })
    else
      if request.xhr? && request.format.html?
        render partial: 'form', locals: { comment: @comment }, layout: false, status: :bad_request
      else
        render 'new'
      end
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :privacy)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def title(page_title)
    content_for(:title) { page_title }
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/comments/_comment.html.slim
li
  => comment.content.to_s.html_safe
  | at
  =< local_time(comment.created_at)

app/views/comments/_form.html.slim
- # Optional variables: comment

= bootstrap_form_for comment,
    remote: true,
    html: { data: { controller: "remote-form" } } do |form|

    = form.select :privacy, Comment::PRIVACIES, { include_blank: true }, { "data-controller" => "selectize" }
    = form.rich_text_area :content, hide_label: true, placeholder: "Type your comment here...", autofocus: true

    = form.submit "Post", "data-disable-with" => "Posting..."

app/views/comments/index.html.slim
h3 Comments

.comment-list
  ul.comments-list
    = render @comments

= link_to 'New comment', new_comment_path

app/views/comments/new.html.slim
- title 'New Comment'

.row
  .col-md-12
    h3.my-3= yield(:title)

    = render 'form', { comment: @comment }

= link_to 'Back to comments', comments_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title= yield(:title).presence || "Stimulus Remote Form"
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true
  body
    .container
      = yield